version: '3'

services:
  backend:
    build:
      context: ./ucpa-back-end
    image: backend-image
    ports:
      - "8000:8000"
    depends_on:
      - frontend
      - mysql-db

  frontend:
    build:
      context: ./upca-front-end
      dockerfile: Dockerfile
    image: frontend-image
    ports:
      - "3000:3000"

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: PolishCalculator
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"

